### ISSUE TITLE
Equipping students to critically evaluate their textbooks

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-educators-guide#11]
Proposed chapter from @stevenov.

**Comment by semioticrobotic** [comment]
Hey @stevenov—any update on your progress with this chapter?

**Comment by stevenov** [comment]
I'm just waiting on one collaborator, who's been away, to sign off on it! It's written, with sentences and everything!

**Comment by semioticrobotic** [comment]
A chapter with sentences even? How _fancy_! (Thanks, @stevenov! You rock!)

**Comment by semioticrobotic** [comment]
Just checking on that final draft, @stevenov. Have your collaborators signed off just yet? If so, we can work to get it typeset by the end of this coming week.

**Comment by stevenov** [comment]
Two of the three! I'm shooting for the final green light this week.

**Comment by afchernik** [comment]
The authors explain that they wanted to bring students into the process of evaluating how textbooks are working (and not working) for students. Do you think faculty at your own organization would push back against the idea of opening textbook selection and evaluation to students? Why or why not? What are some strategies you could use to help faculty appreciate the need for a more collaborative approach to selecting texts?
 
The authors raise the issue of “textbook economics,” noting that even though OER have a favorable price, some students would opt to pay for commercial textbooks because of the features these texts offer. What kinds of features are worth paying for? What do these features add to the learning process? Is there a way to replicate or improve upon these features in OER?
 
While the idea of going open with the processes and products of the authors’ seminar project was a powerful one, the authors explain that ultimately continuing the project proved unsustainable. Why? Do these problems related to sustainability resonate with your own efforts to go open? What are strategies or some possible solutions to these problems?
