### ISSUE TITLE
Economics, openness, and the education system

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-educators-guide#5]
Chapter proposal from Rahul Razdan:
> Openness has been a powerful driver in fields such as software development. This book examines open principles' potential to drive innovation in the area of education. However, before prescribing future remedies, we should  understand some of the fundamental historical, social, and economic  forces driving the current education system in the United States. Only with that understanding can we outline future pathways for reform.

**Comment by engineerteacher** [comment]
Possible questions:

1. The author provides a compelling analysis of how the current industrial model of education has evolved based on the optimization of two scarce resources: the instructor and the classroom. What are ways that this model has either been beneficial or problematic to your own educational career? 
2. As a follow up to the above question, what are ways that the Open Organization principles can make the traditional model more equitable for all students?
3. In what ways does the learning organization you work the closest with embrace developments in openness, technology, and networking to shift the fundamental paradigm of the industrial model, especially with regard to development and delivery of instructional IP and early career discovery?
4. The author accurately articulates the problem many students face in high school and college (and probably elsewhere) when operating within a teacher-as-craftman system. What specific changes would you recommend to still leverage the unique skills and talents of teachers, but also leverage the principles of openness to eliminate variability and improve consistency?

**Comment by semioticrobotic** [comment]
Killer questions, @engineerteacher!

**Comment by trncb** [comment]
Some copyediting suggestions:

**Economics**

*1st paragraph:*
Remove double spaces between "should  understand" and "economic  forces"

*2nd paragraph:* Changed the tense of this sentence
from
"In order to manage delivery costs, the class must move in lock-step, and students must begin at a similar level of skill."
to
"In order to manage delivery costs, the class needed to move in lock-step, therefore requiring the students to begin at a similar skill level."

*2nd paragraph:* (optional) Make this part for succinct
from "... the vast majority of educational ..." to "... most educational ..."

*2nd paragraph:* (optional) make a new paragraph at this point
"Further, as one proceeds ..."

*2nd paragraph:* (optional) Make this line flow better
From "Further, as one proceeds up the academic ladder ..." to "As one proceeds further up the academic ladder ..."

*2nd paragraph:*
from "... system in a negative light. But two points ..."
to "... system in a negative light, but two points ..."

*Banked learning point:*
Remove double spaces "classroom,  students"

From "... generally bored. And students ..."
to "... generally bored. While students ..."

*Imprisoned Time/Space point:*
Changed function
from "Students who function badly in ..."
to "Students who struggle to function during ..."

*plural to singular*
From: "... early mornings (medically documented for teenagers) or mid-afternoons ..."
To "... early morning (medically documented for teenagers) or mid-afternoon ..."

*Multiple shallow distributed class point:*
Consist U.S. spelling "over-emphasised" to "over-emphasized"

**Differentiation**

*2nd paragraph:*
From "... creates a comic situation ..."
to "... creates a comical situation ..."

Remove double spaces "them  "So ..."

*3rd paragraph:*
From "So we can only ..."
To "So, we can only ..."

**Grading systems**

*1st paragraph:*
Remove double spaces "creates  an" and "entering  the"
Remove space from "... what is the point ?"
remove double space "However,  technology"

**Instruction IP**

**Question:** is it "Instruction IP" or "Instructional IP"? There is reference to both in this article.

*2nd paragraph:*
Remove double space "product,  the"
From "copy-writing" to "copywriting"

*3rd paragraph:*
Remove space " ...enormous inefficiencies ."
Remove double space "... refinement),  hundreds ..."

**Standardization of engagement model**

*1st paragraph:* 
remove double spaces "is teacher-as-craftsman,  every"

**Early career discovery and alumni**

*1st paragraph:*
Added comma from "At best randomly." to "At best, randomly"

*4th paragraph:*
From "... maintain, and deliver active engaging, structured environments ..."
To "... maintain, and deliver engaging and structured environments ..."

From "Further, in this world ..."
To "Furthermore, in this world ..."

**Conclusions**

*1st paragraph:*
From "... also has negative ..."
To "... also have negative ..."

**Review questions**

*3rd point:*
Remove double spaces "recommend  organizations"

**Comment by semioticrobotic** [comment]
Much obliged, @trncb! Incorporated and will appear in a code push today.
