### ISSUE TITLE
Open education is more than open content

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-educators-guide#8]
Proposed chapter from Jim Whitehurst:

> As I shared in The Open Organization, the nature of organizations is changing, because the nature of how we organize to create value is changing. Educational organizations are realizing this more than most, because their stock-in-trade isn't something primarily physical (like apples). It's ideas. And ideas are becoming more plentiful, not less. How we prepare people for life in these new organizations—where an ability to innovate and produce the new is much more important than an ability to work efficiently and reproduce the same—has to change just as significantly. We need to use the power of open to rethink education.

**Comment by afchernik** [comment]
Jim explains that the purpose of education during the Industrial era was to prepare students “to perform rote tasks repeatedly in closed organizations with little contextual perspective,” and that this purpose is outmoded in today’s world. In what ways is the Industrial era model of education outmoded? What do you think the purpose of education is today? Do you think your organization is successfully meeting this purpose?

Jim asks the reader to consider what a classroom might look like if educators were focused on catalyzing rather than directing. How do you understand the difference between a catalyst and a director? Which teaching style is more typical in your organization? What are some benefits and challenges of each style?

Jim observes that “most traditional educational organizations aren’t inclined toward sharing.” What are some examples that he gives to support this statement? Is collaborative academic work by educators valued at your organization? What about this kind of work on the part of students?
